### ISSUE TITLE
IDE support for `native("xxx")`

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1341]
The IDE part of ceylon/ceylon-spec#500 and  ceylon/ceylon-spec#499

 - [x] `Duplicate native implementation` errors.
 - [x] `Module not available for JavaScript platform: ceylon.file "1.1.1"` for the import statement even though it's marked `native("jvm")`

**Comment by quintesse** [comment]
@davidfestal take a look at https://github.com/quintesse/spec500proposal for example code.

Right now I'm getting `Duplicate native implementation` errors.
I'm looking into it but any light you can shine on it would be nice.

I'm also getting `Module not available for JavaScript platform: ceylon.file "1.1.1"` for the import statement even though it's marked `native("jvm")`, probably because the IDE has its own handling of imports.

**Comment by quintesse** [comment]
I solved the duplicate implementation errors.

**Comment by davidfestal** [comment]
OK

**Comment by davidfestal** [comment]
and why was it already working in the CLI ?

**Comment by quintesse** [comment]
Because something got re-sued in the IDE, the Tree was indeed new but somehow the Scope where declarations where looked up was filled with the previous results. I remembered seeing some commented out code about Scopes and now I understood what it was referring to so I adopted the same solution and it seems to work.

**Comment by quintesse** [comment]
Hmm might have been too soon, seems to still have problems

**Comment by davidfestal** [comment]
@quintesse : can you check if your `duplicate ...` errors are still there ? I made some fixes for #1343 that might have fully fixed those also.

**Comment by quintesse** [comment]
Well indeed the duplication errors ae gone, but they just got replaced by new errors, they now say Native implementation must have a header`.
So if you open file `testforjvm.ceylon` you'll see both `testBackend()` and `TestClass` with this error, which is weird because the needed "headers" are right there in the `testimpl.ceylon` file.
And finally it's weird that the errors don't show up in the explorer or the problem view, you actually need to open the file to see them.

**Comment by davidfestal** [comment]
@quintesse : it should be better now.

**Comment by davidfestal** [comment]
the `Module not available for JavaScript platform: ceylon.file "1.1.1"`  error has been fixed by commit : 40ca05f2631b1a39b7fe635573d375a23abed6e1

**Comment by davidfestal** [comment]
@quintesse : can we close this now ?

**Comment by quintesse** [comment]
Well not yet, I'm still getting errors in the test project:

```
Module not meant for this backend: jsonly
Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation. The detail of missing classes is given in the Information markers
```

So that means we still need to handle those `native` annotations on module descriptors (the first error) and something is giving that error about missing classes which we'll need to investigate as well.

**Comment by davidfestal** [comment]
Yes, you're right. I should be able to fix this one easily by including the files of such a module *only* in the file generation step of the related backend.
I'll do this on next Monday.

**Comment by davidfestal** [comment]
This should also have been fully fixed by https://github.com/ceylon/ceylon-js/commit/4b7966de8190037e3edd43802237b7ef6aad78ac

**Comment by quintesse** [comment]
Yes, let's close this, if I find other problems I'll open new issues for them.

**Comment by davidfestal** [comment]
Reopening since the fixes were not good and introduced other bugs native support

**Comment by davidfestal** [comment]
@quintesse, @gavinking  : it should be better now.

Additionally, I implemented the fact that, for the Java backend, we can implement a native declaration in Java. About this point, I created a demonstration project with some small documentation that explains how it works : https://github.com/davidfestal/ceylon-natives-with-java-implementation.
So you will be able to test.

In an IDE point of view, it would be quite easy now to remove the required mapping between Ceylon and Java file names.

**Comment by davidfestal** [comment]
@quintesse : Can I close this now ?

**Comment by quintesse** [comment]
Well I said you could close it last time... before you found more problems yourself ;)
So yes, for me we can close this.

Nice work on that "eylon-natives-with-java-implementation" btw!

**Comment by davidfestal** [comment]
Thanks !
