### ISSUE TITLE
navigation to native language module declarations now takes me straight to Java

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1343]
Previously, if I navigated to, for example, `Integer.plus`, the IDE would pop up a menu with two options, the Ceylon declaration, and the Java declaration. Now it takes me straight to Java.

@davidfestal do you have any clue what happened here? @quintesse is it something to do with your work on `native`?

**Comment by gavinking** [comment]
Apparently there are two model objects for `ceylon.language::String` floating around, and they are not considered equal.

Oh right, yes, it _is_ due to @quintesse's changes.

Lines 327-330 in `Declaration.equals()`. So one `String` is marked as `native`, and the other is not.

@davidfestal The model loader does not set the `nativeBackend1 of the `LazyClass`, so it's null, which is not quite right.

But setting it to `""`, which would fix this bug, doesn't seem quite right either. I'm therefore not quite sure what to do about this.

**Comment by davidfestal** [comment]
I'll have a look on native-relayed issues on next Monday

**Comment by quintesse** [comment]
To be considered equal the declarations must either have no native annotation or the both must have the same one (`"jvm"`, `"js"` or even `""` if it's the header).

I'm not sure though what could be wrong exactly. I'll help you where I can @davidfestal but I'll be away on holidays next week although monday at least I'll be reading my mail so I'll be able to answer any questions you might have @davidfestal

**Comment by quintesse** [comment]
I was thinking that perhaps the types in the language module that are written manually (either the Java versions or JS or both) will probably have information about `native` annotations missing from their meta data. That would cause them to have `null` as the value for `native`.

Given the fact that the language module is built in a special way this doesn't cause us any problems on the compiler side anyway, so the meta data isn't missed.

**Comment by gavinking** [comment]
Well I'm not sure if that definition is correct. I don't know how you arrived at it, and it's certainly not what the IDE is expecting. I would have thought that all native versions of the declaration are in fact the same declaration from the point of view of the type system, but perhaps you have some other reason for treating them as nonequal. I'm not sure.

**Comment by davidfestal** [comment]
In fact it seems to me that the best way would be to manually add the right `native` annotation to the java source code of the language module. it seems to me this would be cleaner, and would avoid managing special cases.

**Comment by gavinking** [comment]
@davidfestal Well that might be _part_ of the solution, but then the IDE would not give me a choice when navigating. It would just take me straight to the Java impl.

**Comment by davidfestal** [comment]
For the rest I want to review the Java-Ceylon source file mapping according to the native changes

**Comment by davidfestal** [comment]
@gavinking : this is now fixed

**Comment by gavinking** [comment]
@davidfestal well it seems to do the right thing for a project with the Java backend enabled. It does _totally_ the wrong thing for a project which is JS-only. I still get sent directly to the _Java_ impl, with no option to view the source.

Also I'm experiencing a brand new bug where `true` and `false` aren't assignable to `Identifiable` on JS-only projects....

**Comment by gavinking** [comment]
And `Sequential` is not a `Correspondence`. So the model loader is now totally broken for JS-only projects :-(

**Comment by davidfestal** [comment]
@gavinking : it should be better after 77df7d2868bef878a8b539a3bdc8a521924ed537

**Comment by gavinking** [comment]
Trying it now.

**Comment by davidfestal** [comment]
@gavinking : Now, kin case of natives,  you have additional hyperlink detectors to navigate to either the Ceylon native declaration header, or the Ceylon Java or Javascript backend-specific implementation.
Can I close the issue now ?

**Comment by gavinking** [comment]
Well, I dunno, @davidfestal, it seems a little flakey. In a JavaScript-only project I have, I can't navigate to `Character.integer` or `Character.whitespace`.

**Comment by gavinking** [comment]
In a Java+JavaScript project it seems to be working OK.

**Comment by davidfestal** [comment]
@gavinking : Now the problems with `Character.integer`, etc are fixed also.
Is it OK for you, so that we can close the issue ?

**Comment by gavinking** [comment]
Well OK that's a big improvement but there are still two things wrong here:

1. Once I navigate to language module Ceylon source, and try to navigate _from_ there, I no longer get the option to navigate to Java. Perhaps that's OK, but it's sort of disappointing.
2. Navigating to a method defined with the new `native` stuff takes me to the Java implementation, not to the header. Perhaps this is an unrelated problem.

**Comment by davidfestal** [comment]
I'll the first point (I see where it comes from), but I don't understand  your second point.

**Comment by davidfestal** [comment]
@gavinking : OK, so the first problem is not related to native changes. It can appear randomly if the workspace has projects with Javascript enabled.

It's because in Javascript-enabled projects, the language module is loaded _from sources, and **not** from binaries_.
And when opening such an archive, the `CeylonParseController` opens the archive file in the context of the first project that contains this module. So if the chosen project is Javascript-enabled, the language module will be source-only, so that hyperlinks from this editor to Java will not be available.

I'll fix it by given the preference, in the `CeylonParseController`, to a project that is Java-only.

However  we should, in the future, review all this to allow Java/JavaScript projects to work with the `loadFromBinaries` option, and even more, to allow several modelLoaders to be used at the same time in a single project. But I think this should happen in the abstracted parts of the IDE, and be implemented when we will implement external module sharing.

**Comment by gavinking** [comment]
@davidfestal OK. I did wonder if it was something like that.

**Comment by gavinking** [comment]
I have:

```ceylon

shared void run() {
    Hello().foo();  //CLICK ON foo HERE
}

shared native class Hello() {
    shared native void foo();
}
shared native("js") class Hello() {
    shared void foo() {
        print("hello js");
    }
}
shared native("jvm") class Hello() {
    shared void foo() {
        print("hello jvm");
    }
}
```

When I click on the invocation of `foo()` it should take me to the native header, not the implementation for JS.

**Comment by davidfestal** [comment]
@gavinking : I've fix your first problem.
As for the second one, you will be able to navigate to the native header when the method overloads will be set on the method declaration. Until now, the `overloads` list is the only used way to link between native header and backend implementation.

**Comment by gavinking** [comment]
This is fixed now, thanks.

**Comment by gavinking** [comment]
@davidfestal This one is back :-( Reopening.

**Comment by davidfestal** [comment]
@gavinking : what is *precisely* the regression ? Can you give an example ?

**Comment by gavinking** [comment]
Thanks @davidfestal.
